### ISSUE TITLE
Angular 11 compiler issue: 'SzSearchHistoryFolioItem' accessor overrides superclass property

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#207]
**Describe the bug**

There is an issue with using the sdk-components-ng in an angular 11 project. I checked the offending code that the compiler is flagging for subclass accessor overriding superclass property and the code hasn't been changed since 2019 so it's nothing _we did_ recently. For some reason the version of typescript or angular-cli in version 11 decided that you can't do that anymore (*rolls eyes*)

I have a quick-fix for this for a patch release.

**To Reproduce**

create a new NG11 app with `ng n test-app --style=scss`
`cd test-app`
`ng add @senzing/sdk-components-ng`
`npm start`

```
- Generating browser application bundles...
ΓêÜ Browser application bundle generation complete.

Initial Chunk Files   | Names  |    Size
styles.css, styles.js | styles | 0 bytes

4 unchanged chunks

Build at: 2021-03-16T18:39:02.705Z - Hash: 0e016b5e613e62ae9ae4 - Time: 2082ms

Error: node_modules/@senzing/sdk-components-ng/lib/models/folio.d.ts:61:9 - error TS2611: 'name' is defined as a property in class 'SzSearchParamsFolioItem', but is overridden here in 'SzSearchHistoryFolioItem' as an accessor.

61     get name(): string;
```

**Expected behavior**
the code compiles.

**Screenshots**
![2021-03-16_131357](https://user-images.githubusercontent.com/13721038/111373702-7babcc80-8659-11eb-83fd-85f530bdf4df.png)

**Additional context**
We should:

- [x] - update offending code (no reason we need the superclass to have public property)
- [x] - update schematics dependencies to include @angular/material (we added this recently)
- [x] - update docs to suggest using `ng add @senzing/sdk-components-ng` instead of `npm i`
- [x] - do local package build
- [x] - install local package build in @angular@^10.0.0 and verify
- [x] - install local package build in @angular@^11.0.0 and verify
- [ ] - tag minor patch version and release
